# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle

image: registry.gitlab.com/m.sciachero/kpassword-store/fedora-java:latest

stages:
  - build
  - test
  - package
  - deploy

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script:
    - yum install mesa-libGL -y
    - ./gradlew check koverXmlReport
  artifacts:
    when: always
    expire_in: 2 hours
    reports:
      junit: "**/build/test-results/test/**/TEST-*.xml"
#      coverage_report:
#        coverage_format: cobertura
#        path: "**/build/reports/xml/cobertura.xml"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

package:
  stage: package
  variables:
    FILE_NAME: kpassword-store-${CI_COMMIT_TAG}-1.x86_64.rpm
    FILE_VERSION: ${CI_COMMIT_TAG}
  script:
    - ./gradlew --build-cache packageRpm
    -  'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file FILE_NAME=build/compose/binaries/main/rpm/${FILENAME} "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/kpassword-store/${FILE_VERSION}/$FILE_NAME"'
  environment: production
  rules:
    - if: $CI_COMMIT_TAG =~ /\d+\.\d+\.\d+/


deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script: echo "should be added"
  environment: production
  rules:
    - if: $CI_COMMIT_TAG =~ /\d+\.\d+\.\d+/
  release:
    name: Release $CI_COMMIT_REF_NAME
    description: './CHANGELOG.md'
    tag_name: "$CI_COMMIT_TAG"