# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: KPassword Store
on:
  push:
    tags:
      - '*'
permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: v${{ github.ref_name}}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
    - name: Install rpm
      uses: ConorMacBride/install-package@v1
      with:
        apt: rpm
    - name: Build release
      uses: gradle/gradle-build-action@v2
      with:
        arguments: packageRpm
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/compose/binaries/main/rpm/kpassword-store-${{ github.ref_name }}-1.x86_64.rpm
        asset_name: kpassword-store-${{ github.ref_name  }}-1.x86_64.rpm
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - uses: actions/upload-artifact@v3
      with:
        path: build/compose/binaries/main/rpm/*

  windows:
    runs-on: windows-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.6.0
      - name: package
        run: ./gradlew packageMsi -i

      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/compose/binaries/main/msi/kpassword-store-${{ github.ref_name}}-1.msi
          asset_name: kpassword-store-${{ github.ref_name }}-1.msi
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}